awc: async_write_coroutine.cc 
	g++ async_write_coroutine.cc -g -o awc -I../../../liburing/src/include -I../folly/include -L../../../liburing/src/ -luring -lpthread -lglog -lgflags -lboost_context -levent -levent_core -lfmt -ldl -liberty -ldouble-conversion -Wall -D_GNU_SOURCE -fpermissive  -fcoroutines -std=c++20

